import gradio as gr
import os
import traceback

from architect.itinerary_planner import plan_trip, retrieve_multimodal


# -------------------------------------------------
# Paths
# -------------------------------------------------
FRAME_FOLDER = r"C:\Users\Pc\OneDrive\Desktop\Travel_itinerary_copy2\data\frames"


# -------------------------------------------------
# Extract Frame Images Safely
# -------------------------------------------------
def extract_frame_images(metas):

    frame_imgs = []

    if metas is None:
        return []

    for meta in metas:

        if not isinstance(meta, dict):
            continue

        src = meta.get("source_file", "")

        if src.endswith(".jpg") or src.endswith(".png"):

            full_path = os.path.join(FRAME_FOLDER, src)

            if os.path.exists(full_path):
                frame_imgs.append(full_path)

    return list(dict.fromkeys(frame_imgs))[:6]

# -------------------------------------------------
# Card format Function
# -------------------------------------------------
import re

def format_itinerary_cards(raw_text):

    # Split into days
    day_sections = re.split(r"(Day \d+:)", raw_text)

    if len(day_sections) <= 1:
        return f"<div class='day-card'>{raw_text}</div>"

    formatted = ""
    model_header = ""

    # Keep model/budget header if exists
    if "Generated By:" in raw_text:
        header_split = raw_text.split("Day 1:")
        model_header = header_split[0]
        raw_text = "Day 1:" + header_split[1]
        day_sections = re.split(r"(Day \d+:)", raw_text)

    formatted += f"<div class='model-header'>{model_header}</div>"

    for i in range(1, len(day_sections), 2):
        day_title = day_sections[i]
        day_content = day_sections[i+1]

        safe_content = day_content.replace("\n", "<br>")

        formatted += f"""
        <div class="day-card">
            <div class="day-title">{day_title}</div>
            <div class="day-content">
                {safe_content}
            </div>
        </div>
        """

    return formatted

# -------------------------------------------------
# Main Function (Optimized)
# -------------------------------------------------
def generate_itinerary(user_query):

    try:
        if not user_query.strip():
            return "❌ Please enter a query.", "⚠️ No evidence yet.", []

        print("STEP 1: Retrieving evidence...")
        docs, metas = retrieve_multimodal(user_query, top_k=3)

        print("STEP 2: Evidence Retrieved Successfully")

        evidence_text = ""
        for doc, meta in zip(docs, metas):
            evidence_text += f"### Source: {meta.get('source_file','unknown')}\n"
            evidence_text += str(doc)[:250] + "\n\n---\n\n"

        print("STEP 3: Generating itinerary...")
        itinerary = plan_trip(user_query, docs, metas)

        print("STEP 4: Itinerary Generated Successfully")

        frame_images = extract_frame_images(metas)

        styled = format_itinerary_cards(itinerary)
        return styled, evidence_text, frame_images

    except Exception:
        error_msg = traceback.format_exc()

        return (
            "❌ Error while generating itinerary.",
            f"## 🔥 Full Debug Error:\n```python\n{error_msg}\n```",
            []
        )


# -------------------------------------------------
# Tokyo Neon Theme CSS
# -------------------------------------------------
custom_css = """
body {
    background: radial-gradient(circle, #1a001a, #000000);
}

h1 {
    font-size: 50px;
    font-weight: 900;
    text-align: center;
    color: #FFFFFF;
    text-shadow: 0px 0px 18px rgba(255,45,150,0.9);
}

h3 {
    font-size: 30px;
    font-weight: 900;
    text-align: center;
    color: #FFFFFF;
    text-shadow: 0px 0px 18px rgba(255,45,150,0.9);
}

.gr-box {
    border-radius: 20px !important;
    background: rgba(0,0,0,0.65) !important;
    backdrop-filter: blur(12px);
}

/* Tabs Title Size */
button[role="tab"] {
    font-size: 22px !important;
    font-weight: 800 !important;
}

.gr-button {
    border-radius: 16px !important;
    font-size: 18px !important;
    font-weight: 700 !important;
    background: linear-gradient(to right, #ff2d77, #ff7eb3) !important;
    border: none !important;
}

/* ============================= */
/* MODEL HEADER STYLE */
/* ============================= */
.model-header {
    font-size: 18px;
    margin-bottom: 20px;
    color: #ff9ecb;
}

/* ============================= */
/* DAY CARD STYLE */
/* ============================= */
.day-card {
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255,45,150,0.4);
    border-radius: 20px;
    padding: 25px;
    margin-bottom: 30px;
    backdrop-filter: blur(12px);
    box-shadow: 0px 0px 20px rgba(255,45,150,0.2);
    transition: 0.3s ease;
}

.day-card:hover {
    transform: translateY(-6px);
    box-shadow: 0px 0px 35px rgba(255,45,150,0.6);
}

/* Day Title */
.day-title {
    font-size: 28px;
    font-weight: 900;
    color: #ff7eb3;
    margin-bottom: 15px;
}

/* Content */
.day-content {
    font-size: 20px;
    line-height: 1.8;
    color: #ffffff;
}

/* ============================= */
/* GOOGLE MAPS BUTTON STYLE */
/* ============================= */
.map-btn {
    display: inline-block;
    margin-top: 8px;
    padding: 8px 14px;
    font-size: 16px;
    font-weight: 700;
    border-radius: 12px;
    text-decoration: none;
    color: white;
    background: linear-gradient(to right, #ff2d77, #ff7eb3);
    box-shadow: 0px 0px 12px rgba(255,45,150,0.6);
    transition: 0.2s ease;
}

.map-btn:hover {
    transform: scale(1.05);
    box-shadow: 0px 0px 20px rgba(255,45,150,0.9);
}
"""


# -------------------------------------------------
# Gradio UI Layout
# -------------------------------------------------
with gr.Blocks() as demo:

    gr.Markdown("<h1>🌏 Tokyo Travel Architect </h1>")
    gr.Markdown("<h3>The world has no price tag. Explore without limits.</h3>")

    gr.Markdown(""" """)

    query_box = gr.Textbox(
        label="✍️ Enter your Tokyo trip query",
        placeholder="Example: plan a 5 day Tokyo hidden gems + street food trip...",
        lines=2
    )

    generate_btn = gr.Button("🗓 Generate My Tokyo Trip")

    with gr.Tabs():

        with gr.Tab("🗓 Final Itinerary"):
            itinerary_output = gr.HTML()

        with gr.Tab("📚 Evidence Used"):
            evidence_panel = gr.Markdown()

        with gr.Tab("🖼 Frames Gallery"):
            frame_gallery = gr.Gallery(
                label="Retrieved Frames",
                columns=2,
                height=350
            )

    generate_btn.click(
        fn=generate_itinerary,
        inputs=query_box,
        outputs=[itinerary_output, evidence_panel, frame_gallery],
        show_progress=True
    )


# -------------------------------------------------
# Launch App
# -------------------------------------------------
if __name__ == "__main__":
    demo.launch(
        theme=gr.themes.Soft(),
        css=custom_css,
        allowed_paths=[FRAME_FOLDER]
    )